 --Создала излишне сложную структуру только лишь из соображения тренировки

CREATE TABLE VALUTE_INFO(
VALUTE_ID INT PRIMARY KEY,
VALUTE_NAME VARCHAR
);


CREATE TABLE CURS_INFO(
VALUTE_ID INT ,
DATA TIMESTAMP ,
CURS DECIMAL,
  CONSTRAINT PK_CURS_INFO PRIMARY KEY (VALUTE_ID, DATA),
  CONSTRAINT FK_CURS_INFO FOREIGN KEY (VALUTE_ID)
    REFERENCES VALUTE_INFO(VALUTE_ID)
);
