spring:
    datasource:
        driverClassName: 'org.postgresql.Driver'
        url: 'jdbc:postgresql://localhost:5432/education_db'
        username: 'postgres'
        password: 'postgres'
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
        show-sql: 'true'
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false

webService:
    uri : "http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx"

xsdPath: "C://LEARN/EducationProject/daily-info-ws/src/main/resources/xsd/ValuteData.xsd"

